### ISSUE TITLE
Configuration URI problems

### ISSUE THREAD

**Issue by deverie** [jgraichen/msgr#13]
Hello. First let me start by saying that this gem is fantastic. It's made integrating RabbitMQ into our Rails project very smooth. That being said I did run in to one problem when setting configuration information.

We're connecting to cloudamqp.com through Heroku and were provided with a preconfigured server, vhost, etc. I'm able to successfully connect to the service using utilities such as Bunny, rabbitmqadmin, etc. while passing each configuration option separately. However when trying to use the URI (amqp://my_user:password@something.something.cloudamqp.com/my_vhost) value in rabbitmq.yml I have no such luck. I receive the following error when trying to connect: 

```
Connection-level error: NOT_ALLOWED - access to vhost '/my_vhost' refused for user 'my_user' (Bunny::NotAllowedError)
```

It looks like when the config is [parsed](https://github.com/jgraichen/msgr/blob/cfe2a803ba968fd7240d69a9a90e4225713b25b0/lib/msgr/client.rb#L18) the :vhost option is set to "/vhost" but I need it to be "vhost" in order to connect.

That being said, would it be possible to provide the configuration details as separate values?

Eg.
```yml
# rabbitmq.yml
common: &common
  host: servername
  pass: password
  vhost: vhost
  user: username
...
```

I'm new to AMQP so please let me know if I'm way off base or if there's anything I can do to correct for this connection problem.

Thanks again for writing such a useful tool!

**Comment by jgraichen** [comment]
I pushed a fix to fully support additional hash keys. You should be able to configure all keys in addition to the URI. The URI itself is still required and parsed in the same old way to not break API. You should be able to override the vhost separately:

```
production:
  uri: amqp://localhost/any_vhost
  vhost: real_vhost
```

I'll release a new version soon. Please contact me if anything breaks.
