### ISSUE TITLE
Magr::Route does not support namespaced consumer classes

### ISSUE THREAD

**Issue by Adsidera** [jgraichen/msgr#48]
If a consumer class needs to be namespaced for business reasons, it seems there is currently no way to correctly route it, as `Msgr::Route` recognizes routing only to `consumer_class#action` patterns. Namespacing to `module_name/consumer_class#action` triggers the `ArgumentError  Must be consumer_class#action.`

**Comment by franzliedke** [comment]
I already have a branch where this is 80% working. :)

I checked the RabbitMQ docs and apparently colons would be allowed to use in queue names. Any objections against that, @jgraichen? It could look like this: `msgr.consumer.Namespace::FooConsumer.some_action`.

**Comment by franzliedke** [comment]
@Adsidera Just released with 1.4.0. 😄
